In [3]:
import numpy


In [4]:
numpy


<module 'numpy' from '/home/josi/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'>

In [6]:
numpy.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
numpy.arange(5, 10, .1)

array([5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2,
       6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5,
       7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8,
       8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [11]:
a = numpy.array([3,6,4,9]) 

In [13]:
a

array([3, 6, 4, 9])

In [16]:
a.sum()


22

In [18]:
numpy.diff(a)

array([ 3, -2,  5])